### ISSUE TITLE
站点，mt现在不支持了

### ISSUE THREAD

**Issue by chenyangchina** [Mattoids/nas-tools#10]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.2.7
>
> 环境:Synology
>

## 你遇到什么问题了？

> mt现在不支持了
![image](https://github.com/Mattoids/nas-tools/assets/40290444/375db3d6-4e98-4f8e-84fd-60ac66bb9fba)
## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Mattoids** [comment]
最新版本已经修复了这个问题，请尝试更新版本
