### ISSUE TITLE
无法用127.0.0.1访问2.8.1

### ISSUE THREAD

**Issue by 8423ffsf** [Mattoids/nas-tools#4]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.9.1
>
> 环境: windows
>

## 你遇到什么问题了？

> 只能用localhost访问，用127.0.0.1访问提示拒绝连接（ps：测试2.9.3时127.0.0.1能够访问）

## 已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

## 你期望的结果

> 能够正常访问

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
![捕获](https://github.com/Mattoids/nas-tools/assets/105541211/24515a2c-675a-4ba5-9333-ca6c6d4ed03b)
![捕1获](https://github.com/Mattoids/nas-tools/assets/105541211/16b051fd-92d2-4931-baff-8f0521d83b64)

**Comment by Mattoids** [comment]
你所说的问题是  windows 版本吗？
然后就是nas-tools的版本号确认是2.9.1？

据我所知，当前项目没有支持这个版本的。是否描述有问题

**Comment by 8423ffsf** [comment]
更正：2.8.1   平台win，当时打错了

**Comment by 8423ffsf** [comment]
@Mattoids windows版本确认，2.9.1确认，是较老的版本，但是我看到这里几乎是唯一还活跃的仓库，就过来问一下
